spring:
  application:
    name: AI-agent
  profiles:
    active: local


server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.zzh.agentai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: 你的 API Key
logging:
  level:
    org.springframework.ai: DEBUG



